### ISSUE TITLE
설치가 잘 안되네요

### ISSUE THREAD

**Issue by GiJeongCho** [gyupro/Koalpaca-Translation-KR2EN#1]
다운로드 이후에 gr에서 문제가 다양하게 발생합니다

**Comment by gyupro** [comment]
Gradio를 사용하실때 버그가 있으시면 gradio를 드러내고 테스트해보세요. 아래는 예시 코드입니다.

import os
import torch
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer

MODEL = 'gyupro/Koalpaca-Translation-KR2EN'

model = AutoModelForCausalLM.from_pretrained(
    MODEL,
    torch_dtype=torch.float16,
    device_map='cuda:0'
  
)

model.eval()

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=AutoTokenizer.from_pretrained(MODEL),
)

text = '지금 뭐해?'
ans = pipe(
    f"### source: {text}\n\n### target:",
    do_sample=False,
    max_new_tokens=2048,
    temperature=0.7,
    top_p=0.9,
    return_full_text=False,
    eos_token_id=2,
)

msg = ans[0]["generated_text"]
print(msg)

**Comment by GiJeongCho** [comment]
오오 답장 빠르시네요 감사하짐나 혹시 graio 버젼이 어떻게 되실까요?
-----Original Message-----

**Comment by gyupro** [comment]
gradio==3.41.1 이에요

**Comment by GiJeongCho** [comment]
numpy
transformers>=4.26.1
torch
sentencepiece
tokenizers==0.12.1
gradio==3.41.1
accelerate

requirements.txt 이렇게 바꾸면 좋겠네요 !! 이제 잘 됩니다 감사합니다
-----Original Message-----

**Comment by gyupro** [comment]
조언 감사합니다.
